[tool.poetry]
name = "wiki_tool_python"
version = "0.1.0"
description = "Script to perform tasks with websites on MediaWiki engine using API"
authors = ["Artiom Khandamirov <t9max@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.22"
Click = "^7.0"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-docstrings = "^1.5.0"
flake8-bandit = "^2.1.2"
flake8-deprecated = "^1.3"
autopep8 = "^1.4"
mypy = "^0.730"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
